### ISSUE TITLE
Train test split

### ISSUE THREAD

**Issue by mahdiabdollahpour** [skoltech-nlp/paradetox#1]
Hi

Thanks for releasing the dataset.

 I had a question regarding the train-test split mentioned in the paper. Which rows of the files [/paradetox/paradetox.tsv](https://raw.githubusercontent.com/s-nlp/paradetox/main/paradetox/paradetox.tsv) are the train samples, and which rows are the test samples?

**Comment by dardem** [comment]
Hello!

You can write me a personal email (dardem96@gmail.com) and I will send you the test set of the task.

Best,
Daryna
