### ISSUE TITLE
The test part of the dataset?

### ISSUE THREAD

**Issue by Junlong-Wang** [skoltech-nlp/paradetox#2]
Hello, I'm interested in text detoxification task and your work, but it seems like you didn't release the test part(the 671 sentence pairs)  of the paradetox dataset? It would be much better if you could share that part with me for the further research. Much appreciated!

**Comment by martinigoyanes** [comment]
Yes please, I am also interested in the test part of the dataset

**Comment by dardem** [comment]
Hello!

You can write me a personal email to dardem96@gmail.com and I will send the test part of the data.

Best.
Daryna
