### ISSUE TITLE
error in Calculating CoLA acceptability stats 

### ISSUE THREAD

**Issue by bhaveshk1502** [skoltech-nlp/paradetox#3]
![image](https://user-images.githubusercontent.com/81642316/229216631-7c7cbe4e-a430-4832-9a5c-f2eeef7655a0.png)
full error is Calculating CoLA acceptability stats
---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
[<ipython-input-30-524d5fdaa975>](https://localhost:8080/#) in <cell line: 1>()
----> 1 cola_stats = do_cola_eval(args, preds)
      2 cola_acc = sum(cola_stats) / len(preds)
      3 print('\n')
      4 print(cola_acc)

8 frames
[/content/paradetox/evaluation_detox/metric_tools/fluency.py](https://localhost:8080/#) in do_cola_eval(args, preds, soft)
     71     path_to_data = os.path.join(args.cola_classifier_path, 'cola-bin')
     72 
---> 73     cola_roberta = RobertaModel.from_pretrained(args.cola_classifier_path,
     74                                                 checkpoint_file='checkpoint_best.pt',
     75                                                 data_name_or_path=path_to_data

[/content/fairseq/fairseq/models/roberta/model.py](https://localhost:8080/#) in from_pretrained(cls, model_name_or_path, checkpoint_file, data_name_or_path, bpe, **kwargs)
    367         from fairseq import hub_utils
    368 
--> 369         x = hub_utils.from_pretrained(
    370             model_name_or_path,
    371             checkpoint_file,

[/content/fairseq/fairseq/hub_utils.py](https://localhost:8080/#) in from_pretrained(model_name_or_path, checkpoint_file, data_name_or_path, archive_map, **kwargs)
     80         models = None
     81     else:
---> 82         models, args, task = checkpoint_utils.load_model_ensemble_and_task(
     83             model_path,
     84             arg_overrides=kwargs,

[/content/fairseq/fairseq/checkpoint_utils.py](https://localhost:8080/#) in load_model_ensemble_and_task(filenames, arg_overrides, task, strict, suffix, num_shards, state)
    430                 raise IOError("Model file not found: {}".format(filename))
    431             if state is None:
--> 432                 state = load_checkpoint_to_cpu(filename, arg_overrides)
    433             if "args" in state and state["args"] is not None:
    434                 cfg = convert_namespace_to_omegaconf(state["args"])

[/content/fairseq/fairseq/checkpoint_utils.py](https://localhost:8080/#) in load_checkpoint_to_cpu(path, arg_overrides, load_on_all_ranks)
    348             overwrite_args_by_name(state["cfg"], arg_overrides)
    349 
--> 350     state = _upgrade_state_dict(state)
    351     return state
    352 

[/content/fairseq/fairseq/checkpoint_utils.py](https://localhost:8080/#) in _upgrade_state_dict(state)
    692             state["args"].data = state["args"].data[0]
    693 
--> 694         state["cfg"] = convert_namespace_to_omegaconf(state["args"])
    695 
    696     if "cfg" in state and state["cfg"] is not None:

[/content/fairseq/fairseq/dataclass/utils.py](https://localhost:8080/#) in convert_namespace_to_omegaconf(args)
    388 
    389     # Here we are using field values provided in args to override counterparts inside config object
--> 390     overrides, deletes = override_module_args(args)
    391 
    392     # configs will be in fairseq/config after installation

[/content/fairseq/fairseq/dataclass/utils.py](https://localhost:8080/#) in override_module_args(args)
    310     for k in FairseqConfig.__dataclass_fields__.keys():
    311         overrides.extend(
--> 312             _override_attr(k, FairseqConfig.__dataclass_fields__[k].type, args)
    313         )
    314 

[/content/fairseq/fairseq/dataclass/utils.py](https://localhost:8080/#) in _override_attr(sub_node, data_class, args)
    262                 t_args = v.type.__args__
    263                 if len(t_args) == 1 and (t_args[0] is float or t_args[0] is int):
--> 264                     val = list(map(t_args[0], val))
    265         elif val is not None and (
    266             field_type is int or field_type is bool or field_type is float

TypeError: 'NoneType' object is not iterable

i've tried fixing this but couldn't, can you please take a look into this @dardem @marialysyuk , thank you 
 
notebook for ref: https://colab.research.google.com/drive/14fRSjISxNUGAI4zIbaBc5vHf2DSUgw7Z?usp=sharing

**Comment by dardem** [comment]
Hello Bhavesh!

Such an error can occur if there is somewhere in the dataset an empty string or just randomly non-utf8 encoding symbols. I recommend you to check your input, clean it and delete empty strings from the dataset. That should help. If not, please, let me know.

Best,
Daryna

**Comment by kisialiou** [comment]
@dardem Hello! I have the same problem. It doesn't depend on the dataset since the error occurs during model loading (see traceback above). Maybe you know what could be the issue then? I took the checkpoint and binary data from [here](https://drive.google.com/drive/folders/1p6_3lCbw3J0MhlidvKkRbG73qwmtWuRp).

**Comment by bhaveshk1502** [comment]
@kisialiou try fairseq==10.0, that resolved it for me
